// Code generated by MockGen. DO NOT EDIT.
// Source: internal/storage/storage.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	uuid "github.com/google/uuid"
	domain "github.com/nedokyrill/avito-pr-api/internal/domain"
)

// MockTeamRepositoryInterface is a mock of TeamRepositoryInterface interface.
type MockTeamRepositoryInterface struct {
	ctrl     *gomock.Controller
	recorder *MockTeamRepositoryInterfaceMockRecorder
}

// MockTeamRepositoryInterfaceMockRecorder is the mock recorder for MockTeamRepositoryInterface.
type MockTeamRepositoryInterfaceMockRecorder struct {
	mock *MockTeamRepositoryInterface
}

// NewMockTeamRepositoryInterface creates a new mock instance.
func NewMockTeamRepositoryInterface(ctrl *gomock.Controller) *MockTeamRepositoryInterface {
	mock := &MockTeamRepositoryInterface{ctrl: ctrl}
	mock.recorder = &MockTeamRepositoryInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTeamRepositoryInterface) EXPECT() *MockTeamRepositoryInterfaceMockRecorder {
	return m.recorder
}

// CreateTeamWithMembers mocks base method.
func (m *MockTeamRepositoryInterface) CreateTeamWithMembers(ctx context.Context, teamName string, members []domain.TeamMember) (uuid.UUID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTeamWithMembers", ctx, teamName, members)
	ret0, _ := ret[0].(uuid.UUID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateTeamWithMembers indicates an expected call of CreateTeamWithMembers.
func (mr *MockTeamRepositoryInterfaceMockRecorder) CreateTeamWithMembers(ctx, teamName, members interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTeamWithMembers", reflect.TypeOf((*MockTeamRepositoryInterface)(nil).CreateTeamWithMembers), ctx, teamName, members)
}

// GetTeamByName mocks base method.
func (m *MockTeamRepositoryInterface) GetTeamByName(ctx context.Context, teamName string) (*domain.Team, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTeamByName", ctx, teamName)
	ret0, _ := ret[0].(*domain.Team)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTeamByName indicates an expected call of GetTeamByName.
func (mr *MockTeamRepositoryInterfaceMockRecorder) GetTeamByName(ctx, teamName interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTeamByName", reflect.TypeOf((*MockTeamRepositoryInterface)(nil).GetTeamByName), ctx, teamName)
}

// MockUserRepositoryInterface is a mock of UserRepositoryInterface interface.
type MockUserRepositoryInterface struct {
	ctrl     *gomock.Controller
	recorder *MockUserRepositoryInterfaceMockRecorder
}

// MockUserRepositoryInterfaceMockRecorder is the mock recorder for MockUserRepositoryInterface.
type MockUserRepositoryInterfaceMockRecorder struct {
	mock *MockUserRepositoryInterface
}

// NewMockUserRepositoryInterface creates a new mock instance.
func NewMockUserRepositoryInterface(ctrl *gomock.Controller) *MockUserRepositoryInterface {
	mock := &MockUserRepositoryInterface{ctrl: ctrl}
	mock.recorder = &MockUserRepositoryInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserRepositoryInterface) EXPECT() *MockUserRepositoryInterfaceMockRecorder {
	return m.recorder
}

// GetUserByID mocks base method.
func (m *MockUserRepositoryInterface) GetUserByID(ctx context.Context, userID string) (*domain.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByID", ctx, userID)
	ret0, _ := ret[0].(*domain.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByID indicates an expected call of GetUserByID.
func (mr *MockUserRepositoryInterfaceMockRecorder) GetUserByID(ctx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByID", reflect.TypeOf((*MockUserRepositoryInterface)(nil).GetUserByID), ctx, userID)
}

// SetUserIsActive mocks base method.
func (m *MockUserRepositoryInterface) SetUserIsActive(ctx context.Context, userID string, isActive bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetUserIsActive", ctx, userID, isActive)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetUserIsActive indicates an expected call of SetUserIsActive.
func (mr *MockUserRepositoryInterfaceMockRecorder) SetUserIsActive(ctx, userID, isActive interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetUserIsActive", reflect.TypeOf((*MockUserRepositoryInterface)(nil).SetUserIsActive), ctx, userID, isActive)
}

// MockPullRequestRepositoryInterface is a mock of PullRequestRepositoryInterface interface.
type MockPullRequestRepositoryInterface struct {
	ctrl     *gomock.Controller
	recorder *MockPullRequestRepositoryInterfaceMockRecorder
}

// MockPullRequestRepositoryInterfaceMockRecorder is the mock recorder for MockPullRequestRepositoryInterface.
type MockPullRequestRepositoryInterfaceMockRecorder struct {
	mock *MockPullRequestRepositoryInterface
}

// NewMockPullRequestRepositoryInterface creates a new mock instance.
func NewMockPullRequestRepositoryInterface(ctrl *gomock.Controller) *MockPullRequestRepositoryInterface {
	mock := &MockPullRequestRepositoryInterface{ctrl: ctrl}
	mock.recorder = &MockPullRequestRepositoryInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPullRequestRepositoryInterface) EXPECT() *MockPullRequestRepositoryInterfaceMockRecorder {
	return m.recorder
}

// CreatePullRequestWithReviewers mocks base method.
func (m *MockPullRequestRepositoryInterface) CreatePullRequestWithReviewers(ctx context.Context, pr *domain.PullRequest, reviewerIDs []string, needMoreReviewers bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreatePullRequestWithReviewers", ctx, pr, reviewerIDs, needMoreReviewers)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreatePullRequestWithReviewers indicates an expected call of CreatePullRequestWithReviewers.
func (mr *MockPullRequestRepositoryInterfaceMockRecorder) CreatePullRequestWithReviewers(ctx, pr, reviewerIDs, needMoreReviewers interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatePullRequestWithReviewers", reflect.TypeOf((*MockPullRequestRepositoryInterface)(nil).CreatePullRequestWithReviewers), ctx, pr, reviewerIDs, needMoreReviewers)
}

// GetPullRequestByID mocks base method.
func (m *MockPullRequestRepositoryInterface) GetPullRequestByID(ctx context.Context, prID string) (*domain.PullRequest, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPullRequestByID", ctx, prID)
	ret0, _ := ret[0].(*domain.PullRequest)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPullRequestByID indicates an expected call of GetPullRequestByID.
func (mr *MockPullRequestRepositoryInterfaceMockRecorder) GetPullRequestByID(ctx, prID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPullRequestByID", reflect.TypeOf((*MockPullRequestRepositoryInterface)(nil).GetPullRequestByID), ctx, prID)
}

// MergePullRequest mocks base method.
func (m *MockPullRequestRepositoryInterface) MergePullRequest(ctx context.Context, prID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MergePullRequest", ctx, prID)
	ret0, _ := ret[0].(error)
	return ret0
}

// MergePullRequest indicates an expected call of MergePullRequest.
func (mr *MockPullRequestRepositoryInterfaceMockRecorder) MergePullRequest(ctx, prID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MergePullRequest", reflect.TypeOf((*MockPullRequestRepositoryInterface)(nil).MergePullRequest), ctx, prID)
}

// SetNeedMoreReviewers mocks base method.
func (m *MockPullRequestRepositoryInterface) SetNeedMoreReviewers(ctx context.Context, prID string, needMore bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetNeedMoreReviewers", ctx, prID, needMore)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetNeedMoreReviewers indicates an expected call of SetNeedMoreReviewers.
func (mr *MockPullRequestRepositoryInterfaceMockRecorder) SetNeedMoreReviewers(ctx, prID, needMore interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetNeedMoreReviewers", reflect.TypeOf((*MockPullRequestRepositoryInterface)(nil).SetNeedMoreReviewers), ctx, prID, needMore)
}

// MockPrReviewersRepositoryInterface is a mock of PrReviewersRepositoryInterface interface.
type MockPrReviewersRepositoryInterface struct {
	ctrl     *gomock.Controller
	recorder *MockPrReviewersRepositoryInterfaceMockRecorder
}

// MockPrReviewersRepositoryInterfaceMockRecorder is the mock recorder for MockPrReviewersRepositoryInterface.
type MockPrReviewersRepositoryInterfaceMockRecorder struct {
	mock *MockPrReviewersRepositoryInterface
}

// NewMockPrReviewersRepositoryInterface creates a new mock instance.
func NewMockPrReviewersRepositoryInterface(ctrl *gomock.Controller) *MockPrReviewersRepositoryInterface {
	mock := &MockPrReviewersRepositoryInterface{ctrl: ctrl}
	mock.recorder = &MockPrReviewersRepositoryInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPrReviewersRepositoryInterface) EXPECT() *MockPrReviewersRepositoryInterfaceMockRecorder {
	return m.recorder
}

// GetAssignedReviewers mocks base method.
func (m *MockPrReviewersRepositoryInterface) GetAssignedReviewers(ctx context.Context, prID string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAssignedReviewers", ctx, prID)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAssignedReviewers indicates an expected call of GetAssignedReviewers.
func (mr *MockPrReviewersRepositoryInterfaceMockRecorder) GetAssignedReviewers(ctx, prID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAssignedReviewers", reflect.TypeOf((*MockPrReviewersRepositoryInterface)(nil).GetAssignedReviewers), ctx, prID)
}

// GetPRsByReviewer mocks base method.
func (m *MockPrReviewersRepositoryInterface) GetPRsByReviewer(ctx context.Context, userID string) ([]domain.PullRequestShort, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPRsByReviewer", ctx, userID)
	ret0, _ := ret[0].([]domain.PullRequestShort)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPRsByReviewer indicates an expected call of GetPRsByReviewer.
func (mr *MockPrReviewersRepositoryInterfaceMockRecorder) GetPRsByReviewer(ctx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPRsByReviewer", reflect.TypeOf((*MockPrReviewersRepositoryInterface)(nil).GetPRsByReviewer), ctx, userID)
}

// ReassignReviewerAtomic mocks base method.
func (m *MockPrReviewersRepositoryInterface) ReassignReviewerAtomic(ctx context.Context, prID, oldReviewerID, newReviewerID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReassignReviewerAtomic", ctx, prID, oldReviewerID, newReviewerID)
	ret0, _ := ret[0].(error)
	return ret0
}

// ReassignReviewerAtomic indicates an expected call of ReassignReviewerAtomic.
func (mr *MockPrReviewersRepositoryInterfaceMockRecorder) ReassignReviewerAtomic(ctx, prID, oldReviewerID, newReviewerID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReassignReviewerAtomic", reflect.TypeOf((*MockPrReviewersRepositoryInterface)(nil).ReassignReviewerAtomic), ctx, prID, oldReviewerID, newReviewerID)
}
