// Code generated by MockGen. DO NOT EDIT.
// Source: internal/storage/storage.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	uuid "github.com/google/uuid"
	domain "github.com/nedokyrill/avito-pr-api/internal/domain"
)

// MockTeamRepositoryInterface is a mock of TeamRepositoryInterface interface.
type MockTeamRepositoryInterface struct {
	ctrl     *gomock.Controller
	recorder *MockTeamRepositoryInterfaceMockRecorder
}

// MockTeamRepositoryInterfaceMockRecorder is the mock recorder for MockTeamRepositoryInterface.
type MockTeamRepositoryInterfaceMockRecorder struct {
	mock *MockTeamRepositoryInterface
}

// NewMockTeamRepositoryInterface creates a new mock instance.
func NewMockTeamRepositoryInterface(ctrl *gomock.Controller) *MockTeamRepositoryInterface {
	mock := &MockTeamRepositoryInterface{ctrl: ctrl}
	mock.recorder = &MockTeamRepositoryInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTeamRepositoryInterface) EXPECT() *MockTeamRepositoryInterfaceMockRecorder {
	return m.recorder
}

// CreateTeam mocks base method.
func (m *MockTeamRepositoryInterface) CreateTeam(ctx context.Context, teamName string) (uuid.UUID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTeam", ctx, teamName)
	ret0, _ := ret[0].(uuid.UUID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateTeam indicates an expected call of CreateTeam.
func (mr *MockTeamRepositoryInterfaceMockRecorder) CreateTeam(ctx, teamName interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTeam", reflect.TypeOf((*MockTeamRepositoryInterface)(nil).CreateTeam), ctx, teamName)
}

// GetTeamByName mocks base method.
func (m *MockTeamRepositoryInterface) GetTeamByName(ctx context.Context, teamName string) (*domain.Team, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTeamByName", ctx, teamName)
	ret0, _ := ret[0].(*domain.Team)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTeamByName indicates an expected call of GetTeamByName.
func (mr *MockTeamRepositoryInterfaceMockRecorder) GetTeamByName(ctx, teamName interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTeamByName", reflect.TypeOf((*MockTeamRepositoryInterface)(nil).GetTeamByName), ctx, teamName)
}

// GetTeamMembersByTeamName mocks base method.
func (m *MockTeamRepositoryInterface) GetTeamMembersByTeamName(ctx context.Context, teamName string) ([]*domain.TeamMember, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTeamMembersByTeamName", ctx, teamName)
	ret0, _ := ret[0].([]*domain.TeamMember)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTeamMembersByTeamName indicates an expected call of GetTeamMembersByTeamName.
func (mr *MockTeamRepositoryInterfaceMockRecorder) GetTeamMembersByTeamName(ctx, teamName interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTeamMembersByTeamName", reflect.TypeOf((*MockTeamRepositoryInterface)(nil).GetTeamMembersByTeamName), ctx, teamName)
}

// MockUserRepositoryInterface is a mock of UserRepositoryInterface interface.
type MockUserRepositoryInterface struct {
	ctrl     *gomock.Controller
	recorder *MockUserRepositoryInterfaceMockRecorder
}

// MockUserRepositoryInterfaceMockRecorder is the mock recorder for MockUserRepositoryInterface.
type MockUserRepositoryInterfaceMockRecorder struct {
	mock *MockUserRepositoryInterface
}

// NewMockUserRepositoryInterface creates a new mock instance.
func NewMockUserRepositoryInterface(ctrl *gomock.Controller) *MockUserRepositoryInterface {
	mock := &MockUserRepositoryInterface{ctrl: ctrl}
	mock.recorder = &MockUserRepositoryInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserRepositoryInterface) EXPECT() *MockUserRepositoryInterfaceMockRecorder {
	return m.recorder
}

// CreateOrUpdateUser mocks base method.
func (m *MockUserRepositoryInterface) CreateOrUpdateUser(ctx context.Context, user *domain.User, teamID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateOrUpdateUser", ctx, user, teamID)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateOrUpdateUser indicates an expected call of CreateOrUpdateUser.
func (mr *MockUserRepositoryInterfaceMockRecorder) CreateOrUpdateUser(ctx, user, teamID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateOrUpdateUser", reflect.TypeOf((*MockUserRepositoryInterface)(nil).CreateOrUpdateUser), ctx, user, teamID)
}

// GetUserByID mocks base method.
func (m *MockUserRepositoryInterface) GetUserByID(ctx context.Context, userID string) (*domain.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByID", ctx, userID)
	ret0, _ := ret[0].(*domain.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByID indicates an expected call of GetUserByID.
func (mr *MockUserRepositoryInterfaceMockRecorder) GetUserByID(ctx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByID", reflect.TypeOf((*MockUserRepositoryInterface)(nil).GetUserByID), ctx, userID)
}

// SetUserIsActive mocks base method.
func (m *MockUserRepositoryInterface) SetUserIsActive(ctx context.Context, userID string, isActive bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetUserIsActive", ctx, userID, isActive)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetUserIsActive indicates an expected call of SetUserIsActive.
func (mr *MockUserRepositoryInterfaceMockRecorder) SetUserIsActive(ctx, userID, isActive interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetUserIsActive", reflect.TypeOf((*MockUserRepositoryInterface)(nil).SetUserIsActive), ctx, userID, isActive)
}

// MockPullRequestRepositoryInterface is a mock of PullRequestRepositoryInterface interface.
type MockPullRequestRepositoryInterface struct {
	ctrl     *gomock.Controller
	recorder *MockPullRequestRepositoryInterfaceMockRecorder
}

// MockPullRequestRepositoryInterfaceMockRecorder is the mock recorder for MockPullRequestRepositoryInterface.
type MockPullRequestRepositoryInterfaceMockRecorder struct {
	mock *MockPullRequestRepositoryInterface
}

// NewMockPullRequestRepositoryInterface creates a new mock instance.
func NewMockPullRequestRepositoryInterface(ctrl *gomock.Controller) *MockPullRequestRepositoryInterface {
	mock := &MockPullRequestRepositoryInterface{ctrl: ctrl}
	mock.recorder = &MockPullRequestRepositoryInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPullRequestRepositoryInterface) EXPECT() *MockPullRequestRepositoryInterfaceMockRecorder {
	return m.recorder
}

// CreatePullRequest mocks base method.
func (m *MockPullRequestRepositoryInterface) CreatePullRequest(ctx context.Context, pr *domain.PullRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreatePullRequest", ctx, pr)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreatePullRequest indicates an expected call of CreatePullRequest.
func (mr *MockPullRequestRepositoryInterfaceMockRecorder) CreatePullRequest(ctx, pr interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatePullRequest", reflect.TypeOf((*MockPullRequestRepositoryInterface)(nil).CreatePullRequest), ctx, pr)
}

// GetPullRequestByID mocks base method.
func (m *MockPullRequestRepositoryInterface) GetPullRequestByID(ctx context.Context, prID string) (*domain.PullRequest, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPullRequestByID", ctx, prID)
	ret0, _ := ret[0].(*domain.PullRequest)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPullRequestByID indicates an expected call of GetPullRequestByID.
func (mr *MockPullRequestRepositoryInterfaceMockRecorder) GetPullRequestByID(ctx, prID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPullRequestByID", reflect.TypeOf((*MockPullRequestRepositoryInterface)(nil).GetPullRequestByID), ctx, prID)
}

// MergePullRequest mocks base method.
func (m *MockPullRequestRepositoryInterface) MergePullRequest(ctx context.Context, prID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MergePullRequest", ctx, prID)
	ret0, _ := ret[0].(error)
	return ret0
}

// MergePullRequest indicates an expected call of MergePullRequest.
func (mr *MockPullRequestRepositoryInterfaceMockRecorder) MergePullRequest(ctx, prID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MergePullRequest", reflect.TypeOf((*MockPullRequestRepositoryInterface)(nil).MergePullRequest), ctx, prID)
}

// SetNeedMoreReviewers mocks base method.
func (m *MockPullRequestRepositoryInterface) SetNeedMoreReviewers(ctx context.Context, prID string, needMore bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetNeedMoreReviewers", ctx, prID, needMore)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetNeedMoreReviewers indicates an expected call of SetNeedMoreReviewers.
func (mr *MockPullRequestRepositoryInterfaceMockRecorder) SetNeedMoreReviewers(ctx, prID, needMore interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetNeedMoreReviewers", reflect.TypeOf((*MockPullRequestRepositoryInterface)(nil).SetNeedMoreReviewers), ctx, prID, needMore)
}

// MockPrReviewersRepositoryInterface is a mock of PrReviewersRepositoryInterface interface.
type MockPrReviewersRepositoryInterface struct {
	ctrl     *gomock.Controller
	recorder *MockPrReviewersRepositoryInterfaceMockRecorder
}

// MockPrReviewersRepositoryInterfaceMockRecorder is the mock recorder for MockPrReviewersRepositoryInterface.
type MockPrReviewersRepositoryInterfaceMockRecorder struct {
	mock *MockPrReviewersRepositoryInterface
}

// NewMockPrReviewersRepositoryInterface creates a new mock instance.
func NewMockPrReviewersRepositoryInterface(ctrl *gomock.Controller) *MockPrReviewersRepositoryInterface {
	mock := &MockPrReviewersRepositoryInterface{ctrl: ctrl}
	mock.recorder = &MockPrReviewersRepositoryInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPrReviewersRepositoryInterface) EXPECT() *MockPrReviewersRepositoryInterfaceMockRecorder {
	return m.recorder
}

// AddReviewer mocks base method.
func (m *MockPrReviewersRepositoryInterface) AddReviewer(ctx context.Context, prID, reviewerID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddReviewer", ctx, prID, reviewerID)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddReviewer indicates an expected call of AddReviewer.
func (mr *MockPrReviewersRepositoryInterfaceMockRecorder) AddReviewer(ctx, prID, reviewerID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddReviewer", reflect.TypeOf((*MockPrReviewersRepositoryInterface)(nil).AddReviewer), ctx, prID, reviewerID)
}

// GetAssignedReviewers mocks base method.
func (m *MockPrReviewersRepositoryInterface) GetAssignedReviewers(ctx context.Context, prID string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAssignedReviewers", ctx, prID)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAssignedReviewers indicates an expected call of GetAssignedReviewers.
func (mr *MockPrReviewersRepositoryInterfaceMockRecorder) GetAssignedReviewers(ctx, prID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAssignedReviewers", reflect.TypeOf((*MockPrReviewersRepositoryInterface)(nil).GetAssignedReviewers), ctx, prID)
}

// GetPRsByReviewer mocks base method.
func (m *MockPrReviewersRepositoryInterface) GetPRsByReviewer(ctx context.Context, userID string) ([]domain.PullRequestShort, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPRsByReviewer", ctx, userID)
	ret0, _ := ret[0].([]domain.PullRequestShort)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPRsByReviewer indicates an expected call of GetPRsByReviewer.
func (mr *MockPrReviewersRepositoryInterfaceMockRecorder) GetPRsByReviewer(ctx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPRsByReviewer", reflect.TypeOf((*MockPrReviewersRepositoryInterface)(nil).GetPRsByReviewer), ctx, userID)
}

// RemoveReviewer mocks base method.
func (m *MockPrReviewersRepositoryInterface) RemoveReviewer(ctx context.Context, prID, reviewerID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveReviewer", ctx, prID, reviewerID)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveReviewer indicates an expected call of RemoveReviewer.
func (mr *MockPrReviewersRepositoryInterfaceMockRecorder) RemoveReviewer(ctx, prID, reviewerID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveReviewer", reflect.TypeOf((*MockPrReviewersRepositoryInterface)(nil).RemoveReviewer), ctx, prID, reviewerID)
}
